blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
Auth::routes();
Route::get('/', 'HomeController@index')->name('index');

Route::get('/token/{token}','VerificationController@verify')->name('user.verification');

Route::group(['prefix'=>'admin'],function(){

//admin registration and verification
	Route::post('/register','Auth\Admin\Admin\RegisterController@register')->name('admin.register');
	Route::get('/register/submit','Auth\Admin\Admin\RegisterController@showRegistrationForm')->name('admin.register.submit');
	Route::get('/token/{token}', 'VerifyController@verify')->name('admin.verification');
//admin dashboard
	Route::get('/dashboard', 'AdminController@index')->name('admin.dashboard');
//admin login and logout
	Route::get('/login','Auth\Admin\Admin\LoginController@showLoginForm')->name('admin.login');
	Route::post('/login/submit','Auth\Admin\Admin\LoginController@login')->name('admin.login.submit');
	Route::post('/logout','Auth\Admin\Admin\LoginController@logout')->name('admin.logout');
//admin Forgotpassword and reset password
	Route::post('/password/email','Auth\Admin\Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('/password/reset','Auth\Admin\Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::get('/password/reset/{token}','Auth\Admin\Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('/password/reset','Auth\Admin\Admin\ResetPasswordController@reset')->name('admin.password.reset.post');




});

//order route details
Route::group(['prefix'=>'/orders'],function(){

	Route::get('/',"OrderController@index")->name('orders.index');
	Route::get('/create',"OrderController@create")->name('orders.create');
	Route::post('/store',"OrderController@store")->name('orders.store');
	Route::get('/show/{id}',"OrderController@show")->name('orders.show');
	Route::get('/edit/{id}',"OrderController@edit")->name('orders.edit');
	Route::post('/update/{id}',"OrderController@update")->name('orders.update');
	Route::post('/delete/{id}',"OrderController@destroy")->name('orders.destroy');

	//paid and Complete
	Route::post('/paid/{id}',"OrderController@orderPaid")->name('orders.paid');
	Route::post('/complete/{id}',"OrderController@orderComplete")->name('orders.complete');

});
Route::group(['prefix'=>'/categories'],function(){

//cotegories route details
Route::get('/',"CategoryController@index")->name('categories.index');
Route::get('/create',"CategoryController@create")->name('categories.create');
Route::post('/store',"CategoryController@store")->name('categories.store');
Route::get('/edit/{id}',"CategoryController@edit")->name('categories.edit');
Route::post('/update/{id}',"CategoryController@update")->name('categories.update');
Route::post('/delete/{id}',"CategoryController@delete")->name('categories.delete');

});







Route::get('/user/dashboard',"UserController@dashboard")->name('dashboard');
Route::get('/dashboard/profile',"UserController@profile")->name('dashboard.profile');
Route::post('/dashboard/update',"UserController@update")->name('dashboard.update');
Route::post('/dashboard/delete/{id}',"UserController@destroy")->name('user.destroy');


//products route details
Route::resource('products','ProductController');
Route::get('/product-manage','ProductController@product_manage')->name('product-manage');
Route::get('/product-search','HomeController@product_search')->name('product-search');
Route::get('/categories-show/{id}',"ProductController@categories_show")->name('categories-show');

//cotegories route details

//brands route details
Route::get('/brands',"BrandController@index")->name('brands.index');
Route::get('/brands/create',"BrandController@create")->name('brands.create');
Route::post('/brands',"BrandController@store")->name('brands.store');
Route::get('/brands/show',"BrandController@show")->name('brands.show');
Route::get('/brands/edit/{id}',"BrandController@edit")->name('brands.edit');
Route::post('/brands/update/{id}',"BrandController@update")->name('brands.update');
Route::post('/brands/delete/{id}',"BrandController@delete")->name('brands.delete');

//card
Route::get('/cards',"CardController@index")->name('cards.index');
Route::get('/cards/create',"CardController@create")->name('cards.create');
Route::post('/cards',"CardController@store")->name('cards.store');
Route::get('/cards/show',"CardController@show")->name('cards.show');
Route::get('/cards/edit/{id}',"CardController@edit")->name('cards.edit');
Route::post('/cards/update/{id}',"CardController@update")->name('cards.update');
Route::post('/cards/delete/{id}',"CardController@destroy")->name('cards.destroy');


//checkout route details

Route::get('/checkout',"CheckoutController@index")->name('checkout.index');
Route::get('/checkout/create',"CheckoutController@create")->name('checkout.create');
Route::post('/checkout',"CheckoutController@store")->name('checkout.store');
Route::get('/checkout/show',"CheckoutController@show")->name('checkout.show');
Route::get('/checkout/edit/{id}',"CheckoutController@edit")->name('checkout.edit');
Route::post('/checkout/update/{id}',"CheckoutController@update")->name('checkout.update');
Route::post('/checkout/delete/{id}',"CheckoutController@destroy")->name('checkout.destroy');

//cities
Route::get('/divisions/ajax/{id}', [
	'uses' => 'PlaceController@divisions_ajax',
	'as' => 'divisions'
]);

Route::get('/districts/ajax/{id}', [
	'uses' => 'PlaceController@districts_ajax',
	'as' => 'districts'
]);

Route::get('/upazilas/ajax/{id}', [
	'uses' => 'PlaceController@upazilas_ajax',
	'as' => 'upazilas'
]);

blog/resources/views/Partial/all-products.blade.php
<div class="widget">
	<div class="product-details" style="color: #fff;background-color: #ccaacc;text-align: center; size: 20px">
		<h4>Product List</h4>
	</div>
	<div class="row">
		@foreach($products as $product)
		<div class="col-sm-4">
			<div class="card margin-top-20">
				@php
				$i=1
				@endphp
				@foreach($product->images as $image)
				@if($i>0)
				<a href="{{route('products.show',$product->slug)}}">
					<img class="card-img-top rounded-circle " src="{{asset('images/products/'.$image->images)}}" alt="Card image">
				</a>
				@endif
				@php
				$i--
				@endphp
				
				@endforeach
				<div class="card-body">
					<div class="products-details">
						<a href="{{route('products.show',$product->slug)}}"><h5 class="card-title">{{$product->title}}</h5></a>
					</div>
					<div class="products-price">
						<p class="card-text">Price: {{$product->price}}</p>
						@include('Cards/card-button')
					</div>
					
				</div>
			</div>
		</div>
		@endforeach
	</div>
</div>

blog/resources/views/Partial/footer.blade.php
<footer class="page-footer font-small cyan darken-3 margin-top-20">
    <div class="container">
      <div class="row">
        <div class="col-md-12 py-5">
          <div class="mb-5 flex-center">
            <a class="fb-ic">
              <i class="fa fa-facebook fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <a class="tw-ic">
              <i class="fa fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <a class="gplus-ic">
              <i class="fa fa-google-plus fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <a class="li-ic">
              <i class="fa fa-linkedin fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <a class="ins-ic">
              <i class="fa fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
            </a>
            <a class="pin-ic">
              <i class="fa fa-pinterest fa-lg white-text fa-2x"> </i>
            </a>
          </div>
        </div>
      </div>

    </div>
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
    </div>

  </footer>

blog/resources/views/Partial/header.blade.php
header.blade.php

blog/resources/views/Partial/messages.blade.php
<div class="container margin-top-20">
	<div class="row">
		<div class="col-xs-8 col-sm-8 col-md-8 offset-xs-2 offset-sm-2 offset-md-2">
			@if($errors->any())
			<div class="alert alert-danger">
				<a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<ul>
					@foreach($errors->all() as $error)
					<p>{{$error}}</p>
					@endforeach
				</ul>
			</div>
			@endif
		</div>
	</div>
</div>
<div class="container margin-top-20">
	<div class="row">
		<div class="col-xs-8 col-sm-8 col-md-8 offset-xs-2 offset-sm-2 offset-md-2">
			@if(Session::has('success'))
			<div class="alert alert-success">
				<p>
					{{Session::get('success')}}
				</p>
			</div>
			@endif
		</div>
	</div>
</div>
<div class="container margin-top-20">
	<div class="row">
		<div class="col-xs-8 col-sm-8 col-md-8 offset-xs-2 offset-sm-2 offset-md-2">
			@if(Session::has('errors'))
			<div class="alert alert-danger">
				<p>
					{{Session::get('errors')}}
				</p>
			</div>
			@endif
		</div>
	</div>
</div>

blog/resources/views/Partial/nav.blade.php
				<nav class="navbar navbar-expand-lg navbar-light bg-light">
					<div class="container">
						<a class="navbar-brand" href="{{ url('/') }}">
							{{ config('app.name', 'E-Commarce') }}
						</a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
						</button>
						<div class="collapse navbar-collapse" id="navbarSupportedContent">
							<ul class="navbar-nav mr-auto">
								<li class="nav-item active">
									<a class="nav-link" href="{{route('index')}}">Home</a>
								</li>
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Products
									</a>
									<div class="dropdown-menu" aria-labelledby="navbarDropdown">
										<a class="dropdown-item" href="{{route('products.index')}}">Products</a>
										<a class="dropdown-item" href="{{route('product-manage')}}">Product Manage</a>
										<a class="dropdown-item" href="{{route('products.create')}}">Product Create</a>
										<!-- <div class="dropdown-divider"></div>
										<a class="dropdown-item" href="#">Something else here</a> -->
									</div>
								</li>
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Categories
									</a>
									<div class="dropdown-menu" aria-labelledby="navbarDropdown">
										<a class="dropdown-item" href="{{route('categories.index')}}">Categories Manage</a>
										<a class="dropdown-item" href="{{route('categories.create')}}">Categories Create</a>
										<!-- <div class="dropdown-divider"></div>
										<a class="dropdown-item" href="#">Something else here</a> -->
									</div>
								</li>
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Drands
									</a>
									<div class="dropdown-menu" aria-labelledby="navbarDropdown">
										<a class="dropdown-item" href="{{route('brands.index')}}">brands Manage</a>
										<a class="dropdown-item" href="{{route('brands.create')}}">brands Create</a>
										<!-- <div class="dropdown-divider"></div>
										<a class="dropdown-item" href="#">Something else here</a> -->
									</div>
								</li>
								<li class="nav-item">
									<form class="form-inline" action="{{route('product-search')}}" method="get">
										<input class="form-control" name="search" type="search" placeholder="Search" aria-label="Search">
										<button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
									</form>
								</li>
								<li  class="nav-item" style="margin-top: 4px;margin-left: 12px">
									<button class="btn btn-danger btn-sm">
										<span class="mt-1">Card</span>
										<span class="badge badge-warnning">
											<a href="{{route('cards.index')}}">{{ App\Card::total_Items() }}</a>
										</span>
									</button>
								</li>
							</ul>
							<ul class="nav navbar-nav navbar-right">
								
								<!-- Authentication Links -->
								@if (Auth::guest())
								<li><a class="btn btn-sm" href="{{ route('login') }}">Login</a></li>
								<li><a class="btn btn-sm" href="{{ route('register') }}">Register</a></li>
								@else
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
										<img src="{{ App\Helper\ImageHelper::getUserImage(Auth::user()->id) }}" alt="" class="img-thumbnail rounded-circle" style="height: 40px;width: 40px">
									</a>
									<ul class="dropdown-menu" role="menu">
										<li>
											<a href="{{ route('dashboard') }}" class="badge badge-success">Dashboard</a>
										</li>
										<li>
											<a href="{{ route('logout') }}"
												onclick="event.preventDefault();
												document.getElementById('logout-form').submit();" class="badge badge-success" style="margin-top: 2px">
												Logout
											</a>
											<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
												{{ csrf_field() }}
											</form>
										</li>
									</ul>
								</li>
								@endif
							</ul>
						</div>
					</div>
				</nav>

blog/resources/views/Partial/products-sidebar.blade.php
<ul class="list-group">
	@foreach(App\Category::orderBy('name','desc')->where('parent_id',NULL)->get(); as $parent)
		<a href="#main-{{$parent->id}}" data-toggle="collapse" class="list-group-item list-group-item-success btn-outline-success"><span><img src="{{asset('images/categories/'.$parent->images)}}" height="50px" width="50px" class="rounded-circle" alt="Los Angeles">{{$parent->name}}</span></a>

		<div class="child-rows collapse 
		@if(Route::is('categories-show'))
			@if(App\Category::ParentOrNotCategory($parent->id,$categories->id))
				   show
			@endif
		@endif
		" id="main-{{$parent->id}}">
			<div class="child-rows">
				@foreach(App\Category::orderBy('name','desc')->where('parent_id',$parent->id)->get(); as $child)
					<a href="{{route('categories-show',$child->id)}}" class="list-group-item list-group-item-wanning 
						@if(Route::is('categories-show'))
						@if($child->id==$categories->id)
						   active
						@endif
					@endif">

					<img src="{{asset('images/categories/'.$child->images)}}" height="40px" width="40px" class="rounded-circle" alt="Los Angeles">{{$child->name}}</a>
				@endforeach
			</div>
		</div>
	@endforeach
</ul>

blog/resources/views/Partial/scripts.blade.php
	<script src="{{ asset('js/slim.min.js') }}"></script>
	<script src="{{ asset('js/propper.min.js') }}"></script>
	<script src="{{ asset('js/bootstrap.min.js') }}"></script>
	<script src="{{ asset('js/jquery-3.2.1.min.js') }}"></script>
	<script src="{{ asset('js/jquery-3.3.1.js') }}"></script>
	<script src="{{ asset('js/dataTables.min.js') }}"></script>
	<script src="{{ asset('js/dataTables.bootstrap4.min.js') }}"></script>