blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
Auth::routes();
Route::get('/', 'HomeController@index')->name('index');

Route::get('/token/{token}','VerificationController@verify')->name('user.verification');

Route::group(['prefix'=>'admin'],function(){

//admin registration and verification
	Route::post('/register','Auth\Admin\Admin\RegisterController@register')->name('admin.register');
	Route::get('/register/submit','Auth\Admin\Admin\RegisterController@showRegistrationForm')->name('admin.register.submit');
	Route::get('/token/{token}', 'VerifyController@verify')->name('admin.verification');
//admin dashboard
	Route::get('/dashboard', 'AdminController@index')->name('admin.dashboard');
//admin login and logout
	Route::get('/login','Auth\Admin\Admin\LoginController@showLoginForm')->name('admin.login');
	Route::post('/login/submit','Auth\Admin\Admin\LoginController@login')->name('admin.login.submit');
	Route::post('/logout','Auth\Admin\Admin\LoginController@logout')->name('admin.logout');
//admin Forgotpassword and reset password
	Route::post('/password/email','Auth\Admin\Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('/password/reset','Auth\Admin\Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::get('/password/reset/{token}','Auth\Admin\Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('/password/reset','Auth\Admin\Admin\ResetPasswordController@reset')->name('admin.password.reset.post');




});

//order route details
Route::group(['prefix'=>'/orders'],function(){

	Route::get('/',"OrderController@index")->name('orders.index');
	Route::get('/create',"OrderController@create")->name('orders.create');
	Route::post('/store',"OrderController@store")->name('orders.store');
	Route::get('/show/{id}',"OrderController@show")->name('orders.show');
	Route::get('/edit/{id}',"OrderController@edit")->name('orders.edit');
	Route::post('/update/{id}',"OrderController@update")->name('orders.update');
	Route::post('/delete/{id}',"OrderController@destroy")->name('orders.destroy');

	//paid and Complete
	Route::post('/paid/{id}',"OrderController@orderPaid")->name('orders.paid');
	Route::post('/complete/{id}',"OrderController@orderComplete")->name('orders.complete');

});
Route::group(['prefix'=>'/categories'],function(){

//cotegories route details
Route::get('/',"CategoryController@index")->name('categories.index');
Route::get('/create',"CategoryController@create")->name('categories.create');
Route::post('/store',"CategoryController@store")->name('categories.store');
Route::get('/edit/{id}',"CategoryController@edit")->name('categories.edit');
Route::post('/update/{id}',"CategoryController@update")->name('categories.update');
Route::post('/delete/{id}',"CategoryController@delete")->name('categories.delete');

});







Route::get('/user/dashboard',"UserController@dashboard")->name('dashboard');
Route::get('/dashboard/profile',"UserController@profile")->name('dashboard.profile');
Route::post('/dashboard/update',"UserController@update")->name('dashboard.update');
Route::post('/dashboard/delete/{id}',"UserController@destroy")->name('user.destroy');


//products route details
Route::resource('products','ProductController');
Route::get('/product-manage','ProductController@product_manage')->name('product-manage');
Route::get('/product-search','HomeController@product_search')->name('product-search');
Route::get('/categories-show/{id}',"ProductController@categories_show")->name('categories-show');

//cotegories route details

//brands route details
Route::get('/brands',"BrandController@index")->name('brands.index');
Route::get('/brands/create',"BrandController@create")->name('brands.create');
Route::post('/brands',"BrandController@store")->name('brands.store');
Route::get('/brands/show',"BrandController@show")->name('brands.show');
Route::get('/brands/edit/{id}',"BrandController@edit")->name('brands.edit');
Route::post('/brands/update/{id}',"BrandController@update")->name('brands.update');
Route::post('/brands/delete/{id}',"BrandController@delete")->name('brands.delete');

//card
Route::get('/cards',"CardController@index")->name('cards.index');
Route::get('/cards/create',"CardController@create")->name('cards.create');
Route::post('/cards',"CardController@store")->name('cards.store');
Route::get('/cards/show',"CardController@show")->name('cards.show');
Route::get('/cards/edit/{id}',"CardController@edit")->name('cards.edit');
Route::post('/cards/update/{id}',"CardController@update")->name('cards.update');
Route::post('/cards/delete/{id}',"CardController@destroy")->name('cards.destroy');


//checkout route details

Route::get('/checkout',"CheckoutController@index")->name('checkout.index');
Route::get('/checkout/create',"CheckoutController@create")->name('checkout.create');
Route::post('/checkout',"CheckoutController@store")->name('checkout.store');
Route::get('/checkout/show',"CheckoutController@show")->name('checkout.show');
Route::get('/checkout/edit/{id}',"CheckoutController@edit")->name('checkout.edit');
Route::post('/checkout/update/{id}',"CheckoutController@update")->name('checkout.update');
Route::post('/checkout/delete/{id}',"CheckoutController@destroy")->name('checkout.destroy');

//cities
Route::get('/divisions/ajax/{id}', [
	'uses' => 'PlaceController@divisions_ajax',
	'as' => 'divisions'
]);

Route::get('/districts/ajax/{id}', [
	'uses' => 'PlaceController@districts_ajax',
	'as' => 'districts'
]);

Route::get('/upazilas/ajax/{id}', [
	'uses' => 'PlaceController@upazilas_ajax',
	'as' => 'upazilas'
]);

blog/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['title', 'description', 'slug' ,'quantity', 'price','status','offer_price','brand_id','category_id','user_id'];
    
   public function images()
   {
   	return $this->hasMany('App\Productimage');
   }

   public function user(){
    	return $this->belongsTo('App\User');
    }

    public function brands()
    {
        return $this->belongsTo('App\Brand', 'brand_id');
    }

    public function categories(){
    	return $this->belongsTo('App\Category','category_id');
    }
}

blog/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use App\Brand;
use DB;
use App\Productimage;
use Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class ProductController extends Controller
{

    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('id','desc')->get();
        return view('Products.index',compact('products'));
    }

    public function product_manage()
    {
        $products = Product::orderBy('id','desc')->get();
        return view('Products.product-manage',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brands=Brand::orderBy('id','desc')->get();
        return view('Products.create',compact('brands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,
            [
            'title'=>'required|max:50|min:5',
            'description'=>'required',
            'price' =>'required',

            ]
    );

        $input = $request->all();
        $input['user_id'] = Auth::user()->id;
        $input['slug']=str_slug($request->title);
        $result=Product::create($input);
        $id=$result->id;
        //dd($id);

        if(count($request->images)>0){
            foreach ($request->images as $images) {
                $img=time().'.'.$images->getClientOriginalExtension();
                $location=public_path('images/products/'.$img);
                Image::make($images)->save($location);

                $product_images=new Productimage();
                $product_images->images=$img;
                $product_images->product_id=$id;
                $product_images->save();
            }
        }
        if($result){
            Session::flash('status','Product Created Successfully');
        return redirect('products');
        }else{
            Session::flash('status','Product not Created');
        return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response



     */
    public function show($slug)
    {
        $products=Product::where('slug',$slug)->first();
        //dd($products);
        if(!is_null($products))
        {
            return view('Products.show',compact('products'));
        }else{
            session()->flash('errors','Sorry !! There is no product by this URL');
            return redirect('products');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */


     public function categories_show($id)
    {
        $categories=Category::find($id);
        //dd($categories);
        if(!is_null($categories))
        {
            //dd($categories);
            return view('Categories.show',compact('categories'));
        }else{
            session()->flash('errors','Sorry !! There is no product by this URL');
            return redirect('products');
        }
    }

    public function edit($id)
    {
        $brands=Brand::orderBy('id','desc')->get();
        //dd($brands);
        $product = Product::findOrFail($id);
        return view('Products.edit',compact('product','brands'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,
            [
            'title'=>'required|max:50|min:5',
            'description'=>'required',
            'price' =>'required',

            ]
    );

        $products=Product::findOrFail($id);
        dd($products);
        $products->title=$request->title;
        $products->description=$request->description;
        $products->slug=str_slug($request->title);
        $products->quantity=$request->quantity;
        $products->price=$request->price;
        $products->status=$request->status;
        $products->offer_price=$request->offer_price;
        $products->brand_id=$request->brand_id;
        $products->category_id=$request->category_id;
        $products->user_id=Auth::user()->id;

        if(count($request->images)>0){
            foreach ($request->images as $images) {
                $img=time().'.'.$images->getClientOriginalExtension();
                $location=public_path('images/products/'.$img);
                Image::make($images)->save($location);

                $product_images=new Productimage();
                $product_images->images=$img;
                $product_images->product_id=$id;
                $product_images->save();
            }
        }
        $products->update();
        if($products){
            Session::flash('status','Product Created Successfully');
        return redirect('products');
        }else{
            Session::flash('status','Product not Created');
        return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //dd($id);
        $products=Product::findOrFail($id);
        if(!is_null($products))
        {
            $products->delete();
        }
        session()->flash('success','Product has delete Successfully');
        return back();
    }
}

blog/resources/views/Products/create.blade.php
@extends('Layouts.master')
@section('content')
<div class="container margin-top-20">
    <div class="row">
        <div class="col-xs-8 col-sm-8 col-md-8 offset-xs-2 offset-sm-2 offset-md-2">
            <div class="card-header" style="text-align: center; background-color: #7a7c7c; color: #ffffff;margin-bottom: 20px">
                <strong>Product Create Form</strong>
            </div>
            <form role="form" class="form-horizontal" action="{{route('products.store')}}" method="post" enctype="multipart/form-data">
                {{ csrf_field()}}
                <div class="form-group">
                    <label>title</label>
                    <input type="text" class="form-control" name="title" value="{{ old('title')}}" required>
                    <p class="help-block">{{ ($errors->has('title')) ? $errors->first('title') : ''}}</p>
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea name="description" cols="4" rows="5" class="form-control"required>{{ old('description')}}</textarea>
                    <p class="help-block">{{ ($errors->has('description')) ? $errors->first('description') : ''}}</p>
                </div>
                <div class="form-group">
                    <label>Choose Category</label>
                    <select name="category_id" class="form-control" value="{{old('category_id')}}" required>
                        <option value="0" disabled="true" selected="true">===Select Category===</option>
                        @foreach(App\Category::orderBy('name','desc')->where('parent_id',NULL)->get(); as $parent)
                        <option value="{{$parent->id}}">{{$parent->name}}</option>
                        @foreach(App\Category::orderBy('name','desc')->where('parent_id',$parent->id)->get(); as $child)
                            <option value="{{$child->id}}">---->{{$child->name}}</option>
                        @endforeach
                        @endforeach
                    </select>
                    <p class="help-block">{{ ($errors->has('category_id')) ? $errors->first('category_id') : ''}}</p>
                </div>
                <div class="form-group">
                    <label>Choose Brand</label>
                    <select name="brand_id" class="form-control" value="{{old('brand_id')}}" required>
                        <option value="0" disabled="true" selected="true">===Select Brand===</option>
                        @foreach($brands as $brand)
                        <option value="{{$brand->id}}">{{$brand->name}}</option>
                        @endforeach
                    </select>
                    <p class="help-block">{{ ($errors->has('brand_id')) ? $errors->first('brand_id') : ''}}</p>
                </div>
                <div class="form-group">
                    <label>Quantity</label>
                    <input type="number" name="quantity" class="form-control" value="{{ old('quantity')}}" required>
                    <p class="help-block">{{ ($errors->has('quantity')) ? $errors->first('quantity') : ''}}</p>
                </div>
                <div class="form-group">
                    <label>Price</label>
                    <input type="number" name="price" class="form-control" value="{{ old('price')}}" required>
                    <p class="help-block">{{ ($errors->has('price')) ? $errors->first('price') : ''}}</p>
                </div>
                <div class="form-group">
                    <label>Image</label>
                    <div class="row">
                        <div class="col-sm-4" style="margin-top: 5px">
                            <input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
                        </div>
                        <div class="col-sm-4" style="margin-top: 5px">
                            <input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
                        </div>
                        <div class="col-sm-4" style="margin-top: 5px">
                            <input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
                        </div>
                        <div class="col-sm-4" style="margin-top: 5px">
                            <input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
                        </div>
                        <div class="col-sm-4" style="margin-top: 5px">
                            <input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
                        </div>
                        <div class="col-sm-4" style="margin-top: 5px">
                            <input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
                        </div>
                        <p class="help-block">{{ ($errors->has('images')) ? $errors->first('images') : ''}}</p>
                    </div>
                </div>
                <input type="submit" style="font-size: 20px;" class="btn btn-primary" name="submit" value="Add Product">
            </form>
        </div>
    </div>
</div>
@endsection

blog/resources/views/Products/edit.blade.php
@extends('Layouts.master')

@section('title')
{{$product->title }} || Laravel ecommarce Site
@endsection

@section('content')
<div class="container margin-top-20">
	<div class="row">
		<div class="col-xs-8 col-sm-8 col-md-8">
			@if((Session::get('message')))
			<div class="alert alert-success alert-dismissable">
				<div class="alert alert-success alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
					{{ Session::get('message')}}
				</div>
			</div>
			@endif
			<div class="card-header" style="text-align: center; background-color: #7a7c7c; color: #ffffff;margin-bottom: 20px">
				<strong>Product Create Form</strong>
			</div>
			<form role="form" class="form-horizontal" action="{{route('products.store')}}" method="post" enctype="multipart/form-data">
				{{ csrf_field()}}
				<div class="form-group">
					<label>title</label>
					<input type="text" class="form-control" name="title" value="{{ $product->title }}" required>
					<p class="help-block">{{ ($errors->has('title')) ? $errors->first('title') : ''}}</p>
				</div>
				<div class="form-group">
					<label>Description</label>
					<textarea name="description" cols="4" rows="5" class="form-control"required>{{ $product->description}}</textarea>
					<p class="help-block">{{ ($errors->has('description')) ? $errors->first('description') : ''}}</p>
				</div>

				<div class="form-group">
                    <label>Choose Category</label>
                    <select name="category_id" class="form-control" value="{{old('category_id')}}" required>
                        <option value="0" disabled="true" selected="true">===Select Category===</option>
                        @foreach(App\Category::orderBy('name','desc')->where('parent_id',NULL)->get(); as $parent)
                        <option value="{{$parent->id}}" {{ $parent->id ==$product->category_id ? 'selected' : ''}}>{{$parent->name}}</option>
                        @foreach(App\Category::orderBy('name','desc')->where('parent_id',$parent->id)->get(); as $child)
                            <option value="{{$child->id}}" {{ $child->id ==$product->category_id ? 'selected' : ''}}>--->{{$child->name}}</option>
                        @endforeach
                        @endforeach
                    </select>
                    <p class="help-block">{{ ($errors->has('category_id')) ? $errors->first('category_id') : ''}}</p>
                </div>
                <div class="form-group">
                    <label>Choose Brand</label>
                    <select name="brand_id" class="form-control" value="{{old('brand_id')}}" required>
                        <option value="0" disabled="true" selected="true">===Select Brand===</option>
                        @foreach($brands as $brand)
                        <option value="{{$brand->id}}" {{ $brand->id ==$product->brand_id ? 'selected' : ''}}>{{$brand->name}}</option>
                        @endforeach
                    </select>
                    <p class="help-block">{{ ($errors->has('brand_id')) ? $errors->first('brand_id') : ''}}</p>
                </div>

				<div class="form-group">
					<label>Quantity</label>
					<input type="number" name="quantity" class="form-control" value="{{ $product->quantity }}" required>
					<p class="help-block">{{ ($errors->has('quantity')) ? $errors->first('quantity') : ''}}</p>
				</div>
				<div class="form-group">
					<label>Price</label>
					<input type="number" name="price" class="form-control" value="{{ $product->price}}" required>
					<p class="help-block">{{ ($errors->has('price')) ? $errors->first('price') : ''}}</p>
				</div>
				<div class="form-group">
					<label>Image</label>
					<div class="row">
						<div class="col-sm-4" style="margin-top: 5px">
							<input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
						</div>
						<div class="col-sm-4" style="margin-top: 5px">
							<input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
						</div>
						<div class="col-sm-4" style="margin-top: 5px">
							<input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
						</div>
						<div class="col-sm-4" style="margin-top: 5px">
							<input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
						</div>
						<div class="col-sm-4" style="margin-top: 5px">
							<input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
						</div>
						<div class="col-sm-4" style="margin-top: 5px">
							<input type="file" class="" name="images[]" value="{{ old('images')}}" multiple>
						</div>
						<p class="help-block">{{ ($errors->has('images')) ? $errors->first('images') : ''}}</p>
					</div>
				</div>
				<input type="submit" style="font-size: 20px;" class="btn btn-primary" name="submit" value="Add Product">
			</form>
		</div>
		<div class="col-sm-4">
				<div id="demo" class="carousel slide" data-ride="carousel">
					<!-- The slideshow -->
					<div class="carousel-inner">
						<div class="carousel-inner">
					@php
					$i=1
					@endphp
					@foreach($product->images as $image)
					<div class="carousel-item {{$i==1 ? 'active' : ''}}">
						<img src="{{asset('images/products/'.$image->images)}}" alt="" height=300">
					</div>
					@php
					$i++
					@endphp
					@endforeach
				</div>
					</div>
					<!-- Left and right controls -->
					<a class="carousel-control-prev" href="#demo" data-slide="prev">
						<span class="carousel-control-prev-icon"></span>
					</a>
					<a class="carousel-control-next" href="#demo" data-slide="next">
						<span class="carousel-control-next-icon"></span>
					</a>
				</div>
		</div>
		</div>
	</div>
	@endsection

blog/resources/views/Products/index.blade.php
@extends('Layouts.master')

@section('content')
<section class="margin-top-20">
	<div class="container">
		<div class="row">
			<div class="col-sm-4">
				@include('Partial.products-sidebar')
			</div>
			<div class="col-sm-8">
				@include('Partial.all-products')
			</div>
		</div>
	</div>
	</section><!--service area end -->
	@endsection

blog/resources/views/Products/product-manage.blade.php
@extends('Layouts.master')

@section('content')
<div class="container margin-top-20">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12">
			@if((Session::get('message')))
			<div class="alert alert-success alert-dismissable">
				<div class="alert alert-success alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
					{{ Session::get('message')}}
				</div>
			</div>
			@endif
			<div class="card-header" style="text-align: center; background-color: #7a7c7c; color: #ffffff;margin-bottom: 20px">
				<strong>Product Create Form</strong>
			</div>
			<table id="schedule" class="table table-bordered">
				<thead>
					<tr>
						<th rowspan="2">SL</th>
						<th rowspan="2">title</th>
						<th rowspan="2">Image</th>
						<th rowspan="2">quantity</th>
						<th rowspan="2">price</th>
						<th rowspan="2">Action</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<div style="display: none;">{{$a=1}}</div>
						@foreach($products as $product)
						<td>{{ $a++ }}</td>
						<td>{{ $product->title }}</td>
						<td>
							<div id="demo" class="carousel slide" data-ride="carousel">
								<!-- The slideshow -->
								<div class="carousel-inner">
									<div class="carousel-inner">
										@php
										$i=1
										@endphp
										@foreach($product->images as $image)
										<div style="text-align: center;" class="carousel-item {{$i==1 ? 'active' : ''}}">
											<img class="card-img-top-image" src="{{asset('images/products/'.$image->images)}}" alt="" height=300">
										</div>
										@php
										$i++
										@endphp
										@endforeach
									</div>
								</div>
								<!-- Left and right controls -->
								<a class="carousel-control-prev" href="#demo" data-slide="prev">
									<span class="carousel-control-prev-icon"></span>
								</a>
								<a class="carousel-control-next" href="#demo" data-slide="next">
									<span class="carousel-control-next-icon"></span>
								</a>
							</div>
						</td>
						<td>{{ $product->quantity }}</td>
						<td>{{ $product->price }}</td>
						<td>
							<a href="{{route('products.edit', $product->id)}}" class="btn btn-warning btn-sm">Edit</a>
							<a href="#DeleteModal{{ $product->id}}" data-toggle="modal" class="btn btn-danger btn-sm">Delete</a>
								<div class="modal fade" id="DeleteModal{{$product->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
									<div class="modal-dialog" role="document">
										<div class="modal-content">
											<div class="modal-header">
												<h5 class="modal-title" id="exampleModalLabel">Are You Sure To Delete!</h5>
												<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
												</button>
											</div>
											<div class="modal-body">
												<form action="{{ route('products.destroy', $product->id)}}" method="POST">
													{{csrf_field()}}
													{{method_field('DELETE')}}
												<button type="submit" class="btn btn-primary btn-sm">Delete</button>
												</form>
											</div>
											<div class="modal-footer">
												<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
											</div>
										</div>
									</div>
								</div>
								
							</a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
</div>
@endsection

blog/resources/views/Products/show.blade.php
@extends('Layouts.master')

@section('title')
{{$products->title }} || Laravel ecommarce Site
@endsection

@section('content')
<div class="container">
	<div class="row margin-top-20">
		<div class="col-sm-4">
			<div id="demo" class="carousel slide" data-ride="carousel">
				<div class="carousel-inner">
					@php
					$i=1
					@endphp
					@foreach($products->images as $image)
					<div class="carousel-item {{$i==1 ? 'active' : ''}}">
						<img src="{{asset('images/products/'.$image->images)}}" alt="" height=300">
					</div>
					@php
					$i++
					@endphp
					@endforeach
				</div>
				<!-- Left and right controls -->
				<a class="carousel-control-prev" href="#demo" data-slide="prev">
					<span class="carousel-control-prev-icon"></span>
				</a>
				<a class="carousel-control-next" href="#demo" data-slide="next">
					<span class="carousel-control-next-icon"></span>
				</a>
			</div>
		</div>
		<div class="col-sm-8">
			<div class="widget">
				<div class="card">
					<h4 style="text-align: center;">{{$products->title}}</h4>
				</div>
			</div>
			<div class="widget">
				<div class="card">
					<div class="row">
						<div class="col-sm-2">
							<span>Brand Name</span></br>
							<span>Categories</span></br>
							<span>Price</span></br>
						</div>
						<div class="col-sm-7">
							<span>-> {{$products->brands->name}}</span></br>
							<span>-> {{$products->categories->name}}</span></br>
							<span>-> {{$products->price}} Taka only</span>
						</div>
						<div class="col-sm-3">
							<span>{{$products->status}}</span></br>
							<span class="badge badge-primary">{{$products->quantity < 1 ? 'No Item is Available' :$products->quantity.' Item is stock'}}</span></br>
							<span>{{$products->slug}}</span></br>
							<span>{{$products->offer_price}}</span>
						</div>
					</div>
					<h4 style="text-align: center; color: #fff;background-color: pink">Description</h4>
					<p>{{$products->description}}</p>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection